services:
  - type: web
    name: gang-boyz-ecommerce
    env: node
    plan: free
    buildCommand: ./build.sh
    startCommand: npm run start
    nodeVersion: 22
    envVars:
      - key: NODE_ENV
        value: production
      - key: NPM_CONFIG_PRODUCTION
        value: "false"